// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/offline": {
    params: {};
  };
  "/api/sync": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/history" | "/login" | "/offline" | "/api/sync";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/offline.tsx": {
    id: "routes/offline";
    page: "/offline";
  };
  "routes/api.sync.tsx": {
    id: "routes/api.sync";
    page: "/api/sync";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/history": typeof import("./app/routes/history.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/offline": typeof import("./app/routes/offline.tsx");
  "routes/api.sync": typeof import("./app/routes/api.sync.tsx");
};